### ISSUE TITLE
[EntityBase] Parameterless NotifyPropertyChanged with CallerMemberName (.NET 4.5)

### ISSUE THREAD

**Issue by tonysneed** [tonysneed/trackable-entities#27]
We should add a parameterless overload of NotifyPropertyChanged in [EntityBase] (https://github.com/azabluda/TrackableEntitiesContrib/blob/e7454fd0fee9876a9e897039c89ab1ad918a4830/Source/TrackableEntities.Client/EntityBase.cs) that includes the CallerMemberName attribute:

```csharp
private void NotifyPropertyChanged([CallerMemberName] string propertyName = string.Empty())
{
    if (PropertyChanged != null)
    {
        PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    }
}
```
We will need to surround this with a pre-compile directive excluding the method for .NET 4.

Classes that extend EntityBase should be refactored to call this method, as well as code-gen templates.

This is to follow up #26. @azabluda Does this look alright to you?

**Comment by azabluda** [comment]
Sounds good to me!
