### ISSUE TITLE
[EntityBase] Move EntityBase to Common?

### ISSUE THREAD

**Issue by tonysneed** [tonysneed/trackable-entities#34]
Should we move EntityBase into the Common assembly so that it will be shared between client and server?
- This will enable the use of Add Service Reference for WCF projects
- The VS template wizards be happier with shared entities if no need to reference client package from server
- Consolidating entities into a single assembly will result in fewer projects and less clutter

**Comment by tonysneed** [comment]
@azabluda What do you think about this?

**Comment by azabluda** [comment]
This is exactly how we use TE in our project. Both client and server sides share the same entity classes and thus reference both TE.Common and TE.Client. We even don't mind if ChangeTrackingCollection class is performing change tracking on both ends.

I basically see two possibilities: we either move only EntityBase (together with IIdentifiable of course) to Common, or simply merge TE.Common and TE.Client into just one TE library.

**Comment by tonysneed** [comment]
What I'd like to do is keep Common separate, but allow the server-side to reference Client if they wish to bring in change-tracking on the server-side.  It's just my penchant for SoC. :sunglasses: 

We'll need to move `IIdentifiable` to Common together with EntityBase.  And I'll need to configure Common  to target .NET 4.5, instead of 4.0, so that `CallerMemberName` will be supported.  I'll then remove dependency of Client.Net4 on Common and instead link to the source files.  Client.Net4 will have a version of `EntityBase` without `CallerMemberName`, perhaps using partial classes.

**Comment by tonysneed** [comment]
Actually, this is a little more challenging because `CallerMemberName` is **only** supported on .NET 4.5, and not the other platforms targeted by the PCL for Common.  So the solution is to create a Common.Net45 project and include it in the Common NuGet package with a net45 target, so that it gets picked up by .NET 4.5 clients.

**Comment by irperez** [comment]
I'm new to this, but we use a form of change tracking very similar to this project at my company.  We are evaluating this project for use in our software.  We use change tracking on the server side as well.  So +1 to merge both client and common.

**Comment by tonysneed** [comment]
@irperez Thanks for your input! I'd like to keep change tracking out of the service by default, but to address your scenario I'll provide a sample that pulls in TE.Client to enable server-side change-tracking.  It will be pretty trivial to add that behavior by adding the client package to the server, especially once the new shared entities project template is released with v2.5.

**Comment by tonysneed** [comment]
I'd like to clarify my previous comment: the shared entities project template will by default include the ability to track changes on the server-side, because shared entities will necessarily reference TE.Client, as collection properties will need to be of type `ChangeTrackingCollection`, which is in TE.Client.  So you'll get **both** shared entities and server-side change tracking by default with that template. :smile:

**Comment by tonysneed** [comment]
In keeping with the idea that, in the shared entities template, the service project will reference TE.Client, I'll go ahead and move EntityBase back to TE.Client, where it really belongs.  Then I can remove the dependency in Common on Json.Net.  I'll plan to make the shared entities template the default going forward, but keep the legacy templates for backwards compat.

**Comment by tonysneed** [comment]
Resolved by PR #40.
