### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#44]
Hi Tony, could you take a moment and please reply to this : https://trackable.codeplex.com/discussions/587912

Many Thanks.

**Comment by tonysneed** [comment]
Just posted the reply -- appreciate the nudge. :smile:

**Comment by harrisunderwork** [comment]
Posted some more question. On a side note, is that okay to continue to discussion there or do you recommend any other forum ?
