### ISSUE TITLE
Serialization of "detached/client" entities

### ISSUE THREAD

**Issue by MonDeveloper** [tonysneed/trackable-entities#47]
First of all sir, your trackable-entities rocks!
I worked in a couple of huge projects using the STE and your "paradigm transformation" is exactly what I was looking for except for one missing but important part, the ability to serialize the client graph.

I try to explain it better describing my typical scenario:
1. the human operator, during her daily work open the client (website or winform)
2. she pick up an house (WorkItem) from her work queue (Real Estate Evaluation to do)
3. at this point the client call the service asking all the data related to the house to be evaluated, here EF take part retrieving the whole house graph and passing it to the client
4. here happens the first serialization/deserialization, server model is serialized and the resulting text is deserialized back into the client model, it works!
5. the operator start working in her detached world adding/deleting/changing entities within the graph
6. the operator ends her working days but not her works and she decide to "freeze" the work done so far
7. the system "should" be able to serialize the client graph and save it into a store (File System for example, or a BLOB db column)
8. the day after the operator reopen the same WorkItem deserializing back the graph saved at the previuos point
9. the operator does additional work against the client graph
10. Operator bush the save button and the code ask the ChangeTracker to prepare the "Merge" package to be sent to the service and invoke the service, here happens your second serialization/deserialization where client model is serialized and the resulting text is deserialized back into the service model, it works too!
11. the Service take the "Merge" package, it attach it to a context and save it, after that it return the saved entities to the client
12. the client merge the saved entities to its graph and all the statuses are reconciliated.

*If we remove the point between 6 and 9 (6 and 9 included) your trackable-entities work perfectly, the problem arise with the need to serialize/deserialize from and to client model to add a "shut-down" period in the middle of the client work.*

I think the "problem" (but it is even true that it is the magic that lets your trackable-entities to work so good) is the double nature of the **"ChangeTrackingCollection<TEntity>"**, it works as a "standard" List when the info are within the service and as a "stateful" object when it is within the client, this trick has made the "Collection" (used also to keep the client work done so far) quite difficult to serialize using the most common serializer (DataContractSerializer, XmlSerializer, Json.Net, DataContractXmlSerializer, DataContractJsonSerializer, etc...) without heavily hacking it.

I hope I has been able to describe the "problem" I'm facing replacing the STE with your trackable-entities.

Thanks in advance for your time Tony,
Monducci Marco

**Comment by tonysneed** [comment]
Hello Marco,

Nice to meet you, and thank you for your question! I have good news for you.  ChangeTrackingCollection is serializable just like any other collection, without any special treatment.  Just pick your favorite serializer and you're good to go.  In fact, this is precisely how WCF and Web API transmit these collections between client and service.

To demonstrate this, I have created a GitHub repo: https://github.com/tonysneed/demo-trackable-serialization.  Here I simply use the Json.Net serializer to write customer orders to a file as JSON, then deserialize them back to a change tracking collection.  Have a look and let me know what you think.

The demo ReadMe has instructions for creating the NorthwindSlim database which I am using.  Note that if your graph contains cycles, simply pass a JsonSerializerSettings object with PreserveReferences set to All.

**Comment by harrisunderwork** [comment]
Just chipping for a small point, I was using Microsoft workflows to serialize the entities. I had to add [CollectionDataContract] over ChangeTrackingCollection class to actually make it serializable :)

**Comment by tonysneed** [comment]
@harrisunderwork Actually, [CollectionDataContract] isn't necessary with POCO's (no DataContract or DataMember attributes), which is how [v2.5](https://github.com/tonysneed/trackable-entities/releases/tag/v2.5.0) works.

I've updated the serialization demo to include XML serialization with DataContractSerializer.  I also added settings to handle cycles in the object graph. tonysneed/demo-trackable-serialization@0482db90c08020716d0c4449458adba1a31e9310.

**Comment by MonDeveloper** [comment]
@tonysneed it's not completely true; **ChangeTrackingCollection** is serializable but it has some private members that are lost in case of serialization/deserialization for example the private collection of deleted entities.
Your smart trackable-entities uses the same object **ChangeTrackingCollection** in two different contexts:
1. Within an Entity POCO to represent a NavigationProperty for a 1-to-Many relationship
2. As ChangeTracker at client side (here as a replace for the STE detached logic)

When used in the second scenario, when you connect an entity to keep monitored, the **ChangeTrackingCollection** register its own events and once triggered it store into some private members the imformation about data changed. Thanks to this mechanism it is able to create a package containing all the entities with the appropriate status (deleted, updated, added) that the client can send to the server and the server can attach and Save against the DB, once the DB finishes all the entities are passed back to the client as Unchanged and the **ChangeTrackingCollection** used as ChangeTracker can merge them with the client graph reflecting the update made against the DB.

So, to be able to add a cold shutdown point in time in the middle between
* when I start the  **ChangeTrackingCollection** used as ChangeTracker 
* and when I ask it for the ChangedEntities

this object must offer a serialization that can serialize also all the private properties.

**Comment by MonDeveloper** [comment]
I have forked your demo project and I changed just the Program.cs to show you what I mean.
In my sample the system is NOT working how I need.

https://github.com/MonDeveloper/demo-trackable-serialization.git

**Comment by tonysneed** [comment]
Hello Monducci!

I've re-opened the issue here, so I'll delete the other issue you created.

Alright, I think I understand better now. :)  We just need to get the serializer to include the _deleted items private field (as all the other tracking information is contained in the entities themselves as public properties).  This can be accomplished in a couple of ways.  One would be to add Json and DataMember attributes to that field, but another might be to configure the serializer programmatically.  I'll have a look at at the second approach for now, and I'll push a solution to the demo-trackable-serialization demo I created for this issue.

Out of curiosity, do you prefer Json.Net or the DataContract serializer?  Most of the time, Json would give you better performance.

In terms of your fork, the best would be for you to submit a [pull request](https://help.github.com/articles/creating-a-pull-request) in order to share your code with me.

Cheers!

**Comment by MonDeveloper** [comment]
Sorry for the new Issue I've created, I'm quite new to github and I discovered this one was closed after I replied.

About the Serializer I like both for different reasons, Json.NET is more flexible and DataContractSerializer is much coupled with WCF.
Anyway, for this particular need I think Json.NET could is the better choice.

About the approah, Even I prefer the second approach ("to configure the serializer programmatically") because in this way the "standard" Serialization occurring within WCF can continue working as of today.
If you are interested, I already played this game and I could have some info useful for you:

Using Json.NET Custom serialization I tried two ways:
* Building directly the JsonArray
* Creating a new object that contains the same information contained into the **ChangeTrackingCollection** but without implementing ICollection (all as public properties)
But both failed with Stack Overvlow exception (because the **ChangeTrackingCollection** used as Change Tracker contains entities that contain many **ChangeTrackingCollection** properties, etc...)

Using DataContractSerializer I tried to:
* Define a new class extending your **ChangeTrackingCollection** called **SerializableChangeTrackingCollection** creating a public Getter and Setter for your private fields using reflection, and using this instead of your everywhere (I changed the t4 templates)
Also this tentative failed with an error from DataContractSerilaizer because it doesn't support serialization for "Collection with public Properties"

Hope this info can help you @tonysneed finding out a viable solution.

Thanks for supporting us!
mM

**Comment by tonysneed** [comment]
It took me a while to learn how to work with pull requests in GitHub, but now I love it.  I encourage you to get more familiar with Git and GitHub -- they are the way of the future, especially since Microsoft has fully embraced them.

From what I've read, configuring Json.Net involves creating a custom ContractResolver and overriding CreateProperties.  I'll see what I can come up with and push it to the demo repo.  Cheers!

**Comment by tonysneed** [comment]
It turns out the custom ContractResolver approach does not work with collections.  So instead I opted for serialization callbacks using a SerializableChangeTrackingCollection subclass.  This works for JSON but not XML, because the DataContract serializer does not support serialization callbacks with collection types.  Here is the commit for tonysneed/demo-trackable-serialization@fc6b0016c094f8a168d4409a4e82e6b0cde5f47b.  So if you use Json.Net for serialization, you should be OK.  The cached deletes are restored on serialization and re-cached on deserialization.

**Comment by tonysneed** [comment]
@MonDeveloper, ok to close this issue?
