### ISSUE TITLE
M-2-M Adding existing object to child collection

### ISSUE THREAD

**Issue by johnkattenhorn** [tonysneed/trackable-entities#49]
Can someone remind me how to add existing objects to a TrackableEntities Collection ?

  var entity = await _unitOfWork.QuestionSetRepository.FindAsync(postModel.Id);
  if (entity != null)
  {
    entity.Title = postModel.Title;
    entity.Description = postModel.Description;
    entity.UpdatedBy = User.Identity.Name;
    entity.UpdatedDateTime = DateTime.UtcNow;
    entity.TrackingState = TrackingState.Modified;

    var userList = new List<User>();

    foreach (var selectedUser in postModel.SelectedUsers)
    {
      var user = await _unitOfWork.UserRepository.GetUser(selectedUser.Id);

      if (user != null)
      {
        userList.Add(user);
       }
     }

     entity.Users = userList;
  }

  _unitOfWork.QuestionSetRepository.Update(entity);

I get the usual Primary Key violation and I've forgotten how to do the equivalent of an attach. I've tried adding the child objects directly but that produces the same result.

**Comment by tonysneed** [comment]
Make sure you update your Trackable Entities NuGet packages to the latest version (currently 2.5.1), which includes a fix for this issue #43, as well as related issue #46.

Assuming your entity has a child collection of Users, which is of type ```ChangeTrackingCollection```, then all you have to do is add the user to the property: ```entity.Users.Add(user)```.

For more info, download [TrackableEntities-Samples.zip](https://github.com/tonysneed/trackable-entities/releases/download/v2.5.0/TrackableEntities-Samples.zip) from the [v2.5](https://github.com/tonysneed/trackable-entities/releases/tag/v2.5.0) release, where you'll find a **Relations** sample with code to add, remove and update M2M relations.  You'll also find the sample code [online](https://github.com/tonysneed/trackable-entities/blob/develop/Samples/VS2013/WebApiSample.Relations/WebApiSample.ConsoleClient/Program.cs#L203).

**Comment by johnkattenhorn** [comment]
Thanks Tony; ChangeTrackingCollection lives in the client namespace doesn't it, if I change my Model to this will it screw up my Code First EF Model ?

The code I published earlier is server side, not client side.

**Comment by tonysneed** [comment]
Should be fine, depending on your scenario.

What I recommend is upgrading to v2.5 of the VS extension, then adding a new Entities project to your solution, selecting Shared entities for .NET 4.5. You can then generate your entities the way you did before, with either the CF Model wizard in VS, or the EF Power Tools. Don't forget to update the NuGet packages for TE to v2.5.1.

This will give you support for both inheritance and server-side change tracking.

Are you using WCF or Web API?

**Comment by johnkattenhorn** [comment]
Well it was originally using Web API but the client changed the spec so we've been still using TE but only server side.

**Comment by tonysneed** [comment]
Yeah so I would suggest using Shared entities on the server, even without a client, because the server is where you are updating entities and therefore is also acting as a client.

If you are still using Web API on the service, you'll want to have a look at configuring Json and Xml for matters to handle cycles. You can check out the Web API sample to see how that's done.

**Comment by johnkattenhorn** [comment]
Nah the Web API is gone, it was too complicated apparently :-) Thanks for the tips, I'll upgrade the solution and move the existing code base to the new version. Thanks Tony!

**Comment by tonysneed** [comment]
Interesting!  How is the data access code being hosted?  Now you’ve got me curious. :)

**Comment by johnkattenhorn** [comment]
So the TE services are just being called directly in the controllers, we didn't want to do it that way but the client knows best ;-)

**Comment by tonysneed** [comment]
I see, that explains it. Yes, shared entities will be the best option, and serialization is not a concern.
