### ISSUE TITLE
Detached entities throwing error

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#55]
The entity is detached, so this line is throwing error : 

https://github.com/tonysneed/trackable-entities/blob/develop/Source/TrackableEntities.EF.5/DbContextExtensions.cs#L174

**Comment by tonysneed** [comment]
All entities are detached when ApplyChanges is called.  Can you submit a pull request with a failing unit test?  (You'll be a Git pro in no time!) :smile:

**Comment by harrisunderwork** [comment]
Sure. I'll create a test case for that.

**Comment by harrisunderwork** [comment]
This is related to EF6, when setting state of detached entities throws exception because of various reasons. TE is not right place to handle these exceptions.

Thanks.
