### ISSUE TITLE
GetChanges - Bug - Update Customer.CustomerSetting / Delete Customer.Order

### ISSUE THREAD

**Issue by kaumasse** [tonysneed/trackable-entities#56]
Hi Tony, 

me again. I guess I've found a bug in GetChanges-method of ChangeTrackingCollection.

```csharp
// get Customer with CustomerSetting and Orders
var customer = customerService.GetCustomerAsync("ABC").Result;

var changeTracker = new ChangeTrackingCollection<Customer>(customer);

customer.CustomerSetting.Setting = "Test1";
customer.Orders.Remove(customer.Orders.First());

var changes = changeTracker.GetChanges().SingleOrDefault();
```

| Entity | TrackingState |
------------ | -------------
Customer | Unchanged
CustomerSetting | Modified
Orders[0] | Deleted

Everything fine so far. But if I switch the lines where changes happen... 
```csharp
// get Customer with CustomerSetting and Orders
var customer = customerService.GetCustomerAsync("ABC").Result;

var changeTracker = new ChangeTrackingCollection<Customer>(customer);

customer.Orders.Remove(customer.Orders.First());
customer.CustomerSetting.Setting = "Test1";

var changes = changeTracker.GetChanges().SingleOrDefault();
```
... I got the following result.

| Entity | TrackingState |
------------ | -------------
Customer | Unchanged
CustomerSetting | CustomerSetting is null
Orders[0] | Deleted

CustomerSetting is null, but there should be an entity with TrackingState "Modified".

As soon as I'm more familiar with Github I'll contribute some tests and solutions as well.

Best regards Mathias

**Comment by tonysneed** [comment]
Hi Mathias,

Thanks for submitting the issue.  I recently noticed another problem with ```GetChanges```, so I think we'll need to come up with improved test coverage for that method.  What I noticed is that, after calling ```GetChanges```, cached deleted entities are restored.  However, ```GetChanges``` *should not alter the existing collection in any way*.

Seeing as this could be a great opportunity for you to get more familiar with GitHub :smile:, I'm wondering if you could fork the Trackable Entities repo, create a new branch (for example, bug-getchanges-null), then create a failing unit test (we're using NUnit).  After committing your changes locally, push the commit to GitHub, then you can create a [pull request](https://help.github.com/articles/creating-a-pull-request), which will allow me to have a closer look and make sure I'm fixing the right thing.  Of course, feel free to propose your own fix if you wish. :stuck_out_tongue_winking_eye:

**Comment by kaumasse** [comment]
Hi Tony,

I've added a PR https://github.com/tonysneed/trackable-entities/pull/60.

Mathias

**Comment by kaumasse** [comment]
Hi Tony, do you know when you will release 2.5.2 and whether this bug could be resolved in it? Best regards. Mathias.

**Comment by tonysneed** [comment]
Happy to get the bugs fixed over the weekend.

**Comment by tonysneed** [comment]
PR #65 should resolve this issue.  @kaumasse, can you please get latest, then re-run your tests to see if they pass?

If all is well, I will release TE v2.5.2.

**Comment by kaumasse** [comment]
Hey Tony, 

I've re-run my tests with version 2.5.2 and they worked. Great job, thank you very much! I'll make some more tests in the next weeks. Best regards.

Mathias
