### ISSUE TITLE
ChangeTracking should be disabled before ApplyChanges()

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#62]
I have class A, having child B, and b having child C.

C also has reference of A.

When I am calling ApplyChanges on A, EF is trying to fixup collection of C inside A. Because of that, overridable method InsertItem of ChangeTrackingCollection gets called and which is messing everything.

Thoughts ?

**Comment by tonysneed** [comment]
Trying turning off change tracking in your fixup code for collections, before inserting items.

**Comment by harrisunderwork** [comment]
That's the problem Tony, Fixup events are never fired. Because I am not modifying entities on service end. It is fired by EF itself.

**Comment by tonysneed** [comment]
I'm not familiar with the STE fixup code, but I assume it has a reference to the collection property.  If so, cast it to a ChangeTrackingCollection, so that you can turn off Tracking.

**Comment by harrisunderwork** [comment]
I think somehow, I need to prevent TE walking on reverse entities.

A -> B, I have to prevent ApplyChanges() walking from B -> A.

Does this makes sense ?

**Comment by tonysneed** [comment]
Just set Tracking = false on the collection property, which is of type ChangeTrackingCollection<T>.

**Comment by harrisunderwork** [comment]
That's not the only problem Tony, in our datamodel, we have hierarchical data too, and believe me, there is serious performance issue due to unnecessary recursion. Tracking = false just corrects the odd behavior but I need to take care of performance too.

**Comment by tonysneed** [comment]
So what you're saying is that there are entities in the object graph which you know you don't want to traverse because you know they don't have any changes?

**Comment by harrisunderwork** [comment]
They might have changes, but they might have been visited. Fixup parent references are such entities. Its because TE walks the graph in every direction I think. So it might be walking in the reverse and then again in forward path.

**Comment by tonysneed** [comment]
TE uses a object visitor so that entities are only visited once during traversal.  Do you have a specific example, or can you write a unit test?

**Comment by harrisunderwork** [comment]
Yes I think I can, I will submit one asap.

**Comment by tonysneed** [comment]
Can I hope to get a pull request? :pray:

**Comment by harrisunderwork** [comment]
I think I was wrong, I just tried manually debugging the code, it was working as expected :100: 

I am trying to find out which part of code is taking most of the time and will try to improve it.

For now, closing this issue.

For others, I disabled tracking before calling ApplyChanges() and everything worked as expected.

Thanks.

**Comment by tonysneed** [comment]
Glad to hear! :+1:
