### ISSUE TITLE
Overridable method of GetChanges to get only deleted entities.

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#63]
I have another scenario.

Lets say I have an entity A with navigation property B. B has unique index over foreign key and an extra column required for business purpose. Now I delete an entry of B and insert into collection same entry. So it is like restoring the entity with Added State.

Now since EF performs insert first, index will be violated. Simple solution is first call GetChanges() for deleted entites, SaveChanges, then other Changes and SaveChanges(), all this in a transaction.

Thoughts ?

**Comment by tonysneed** [comment]
If A is related to B as 1-M, how can there be a unique index on the foreign key?  If it's 1-1, then there are two PKs and no FKs.

Logically, deleting and re-inserting the same entity is like not deleting at all and performing an update.  So why not just mark the entity as Modified?

Remember, EF tracks an entity by its primary key.  So EF will only perform an action based on the last EntityState.  Also, remember that a new Tx is created every time SaveChanges is called.

**Comment by harrisunderwork** [comment]
Unique index on foreign key + 1 business key. Logically its an update, but we generate audit too, so we need to show it as deleted and then inserted.

**Comment by tonysneed** [comment]
What you can do is create an outer TransactionScope, then within it, first save the Delete, then save the Insert.  Both will be wrapped in a single tx.

**Comment by harrisunderwork** [comment]
Right, but I would need only deleted entities then, do you think current GetChanges() method can do that ?

**Comment by tonysneed** [comment]
Yes, GetChanges is your ticket there.

**Comment by harrisunderwork** [comment]
I mean I have to create its overridable method right ? Currently there is no such options.

**Comment by tonysneed** [comment]
SaveChanges in DbContext is virtual.

**Comment by harrisunderwork** [comment]
No need to create overridable method, EF takes care of order of queries and my case was messed due to fixup values.
