### ISSUE TITLE
Run NUnit in Visual Studio Express

### ISSUE THREAD

**Issue by azabluda** [tonysneed/trackable-entities#69]
Hi Tony,

Do you have any experience in running TE's NUnit-based tests in Visual Studio Express? The following article worries me a bit http://stackoverflow.com/questions/20907842/how-to-install-nunit-plugin-in-visual-studio-2013-express. Shouldn't we stick to built-in testing framework to encourage the open source community for more active contributions?

Regards,
Alex

**Comment by tonysneed** [comment]
Hi Alex,

I seem to remember you had some issues with NUnit and getting it to work in Visual Studio.  The current "official" testing framework is [xUnit](http://xunit.github.io), which is supported by [Visual Studio](http://xunit.github.io/docs/running-tests-in-vs.html).  It would be great to migrate the tests from NUnit to xUnit.

In terms of Visual Studio editions, be aware that VS Express is now legacy.  Instead developers need to use [Visual Studio Community Edition](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx), which is basically a free version of VS Professional, and it supports running xUnit tests from the built-in Test Explorer. :smile: 

Cheers,
Tony

**Comment by azabluda** [comment]
Thanks for the info! I will try to migrate our tests to xUnit, though I might need your help with SpecFlow tests.

**Comment by tonysneed** [comment]
Terrific, thanks! I'll let you know about the SpecFlow tests.

**Comment by tonysneed** [comment]
Closing this issue as implemented in #70.
