### ISSUE TITLE
Removing an item with TrackingState.Added from ChangeTrackingCollection possible incorrect behavior

### ISSUE THREAD

**Issue by stevedelong** [tonysneed/trackable-entities#74]
I've found an issue when deleting a new item added to a ChangeTrackingCollection.  The sequence of events is as follows:

1) CTC has tracking set to true.
2) New item is created, added to CTC, its state gets set to TrackingState.Added as expected.
3) CTC.Remove(newItem) is called.  Item's state is set to Unchanged, and is added to the CTC's _deletedEntities collection.

Ordinarily this isn't a problem, as GetChanges won't care about it because it's Unchanged.  However, if the item belongs to multiple collections, deleting it means removing it from all of them, which changes the steps to be:

1) CTC1 and CTC2 both have tracking set to true.
2) New item is created, added to CTC1, its state gets set to TrackingState.Added as expected.
3) Item is added to CTC2, its state is already TrackingState.Added and is not changed.
4) CTC1.Remove(newItem) is called.  Item's state is set to Unchanged, and is added to CTC1's _deletedEntities collection.
5) CTC2.Remove(newItem) is called.  Item's state is Unchanged, and is now set to Deleted.  Item is added to CTC2's _deletedEntities collection as well.

If I call GetChanges on either CTC1 or CTC2, I get newItem as a Deleted item, which then fails on an attempt to save because it doesn't actually exist.

My thoughts on a fix for this are to modify TrackableExtensions.SetState so that if it's setting state to Deleted it simply leaves an Added item's state alone vs setting it to Unchanged.  ChangeTrackingCollection.RemoveItem even looks for Added items when determining whether an item should be added to the _deletedEntities collection.

I have a test case that illustrates this issue, but am not sure how best to submit it for you to review, so let me know what you'd like for that.

**Comment by tonysneed** [comment]
Resolved by working with each change tracker independently.  Refactored tests to pass in commit 8e66ad282518ea7618148441ce8ee1d4405e38c9 for pull request #92 [Workarounds for Issues 74-75].
