### ISSUE TITLE
GetChanges can fail to remove restored deletes for items in multiple ChangeTrackingCollections

### ISSUE THREAD

**Issue by stevedelong** [tonysneed/trackable-entities#75]
In a similar vein to the issue I just submitted about deletion of items that belong to multiple ChangeTrackingCollections, I've found a case where GetChanges can leave restored deletes in collections because of where the visitation is checked.

In TrackableExtensions.RemoveRestoredDeletes, the visitation helper is checked before the item is removed from the collection, which works perfectly fine in single-parent cases, but when an item is part of more than one collection, it will only be removed from the first one visited, at which point all others will trip the visitation check and continue prior to being removed from the collection.

In my testing, moving the item removal from after the navigation property iteration to just above the visitation check takes care of this, but I'm not sure what else that might affect.

I have a test case that illustrates the removal failure, but as I said in my other issue, I'm not sure how best to submit it to you.

**Comment by tonysneed** [comment]
Thanks for submitting this issue. Yes, it would help to have a failing unit test. The best way is to fork the repo, create a local branch, then add a unit test to the appropriate test project. Then commit your changes and publish the branch back to GitHub. If you go to the web site you'll then see a button called Compare and Merge (I think). Clicking that button should give you the option to submit a pull request, from which you can reference this issue. Once you've done it a couple times, submitting pull requests will be second nature.

**Comment by stevedelong** [comment]
I’ve submitted a pull request with test cases for the two issues – hopefully I’ve done it properly in a useful way, this is my first-ever GitHub pull request (and in fact, my first GitHub contribution in any form whatsoever).

I’m out of town until 7/20, but will at least try to keep an eye on the tracker until then.

**Comment by tonysneed** [comment]
I'm also on vacation until July 20th, but I'll see if I can have a look at the PR after the kids are in bed. ;)

Congrats on your first pull request and Github contrib!!

**Comment by tonysneed** [comment]
Resolved by working with each change tracker independently.  Refactored tests to pass in commit 8e66ad282518ea7618148441ce8ee1d4405e38c9 for pull request #92 [Workarounds for Issues 74-75].
