### ISSUE TITLE
Question about MVC app

### ISSUE THREAD

**Issue by nhwilly** [tonysneed/trackable-entities#77]
Tony,
Great library - so well documented, thanks for that.  I originally was planning to do a native client app using your library, but that project got cancelled.  Now it looks like this will be an MVC app with an API behind it.  Specifically, I want to use Telerik ASP.NET controls, or maybe their Ajax controls.  

Is this library still a good way to go?  Are there enough benefits in it for those platforms to warrant the added complexity?

Thanks in advance.

**Comment by tonysneed** [comment]
Hi there.  If you're going to be working in the web app space, you should be aware that it has evolved significantly.  If this is a new project, I would suggest taking a serious look at ASP.NET 5, which is currently in a late stage beta and will have a release candidate in November with a go-live license.

In terms of the UI platform, the trend these days is to build single-page apps (SPA's) using a JavaScript framework (or more than one), such as [Angular](https://en.wikipedia.org/wiki/AngularJS).  You can find a great tutorial for using Angular with ASP.NET 5 and MVC 6 [here](http://stephenwalther.com/archive/2015/01/12/asp-net-5-and-angularjs-part-1-configuring-grunt-uglify-and-angularjs).

Hope this helps!

**Comment by nhwilly** [comment]
It helps a lot.  I was planning on using the ASP.NET 5 / MVC 6 approach.  I heard that SPA's are not as search friendly as a standard ASP.NET page is (although now I can't tell you why).

I just really liked the way you had segmented your project space with Unit of Work projects and dependency injection and so on.

I guess TE shines on native apps more than web apps, making the additional complexity somewhat less valuable.  I guess that *someday* there might a native app, but the site would have to be a huge success before that ever happened and even then, I'm not sure that a responsive design wouldn't be just as well received.

There's a possibility that I'll develop a native app in the future and if so, TE might make perfect sense then.
So, thanks for a great library where I learned *a lot* and one of the best documented, fully complete open source offerings I've run across.

Regards...

**Comment by tonysneed** [comment]
As the question seems to have been answered, I'm closing this issue for now.
