### ISSUE TITLE
Changetracking not working, EntityIdentifier is 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by xplatsolutions** [tonysneed/trackable-entities#78]
I'm not sure if it's a bug or doing something wrong.

I have a BaseModel which derives from EntityBase. In my BaseModel I have the following helper methods.

```
        public virtual void OnPropertyChanged<T>(Expression<Func<T>> selectorExpression)
		{
			if (selectorExpression == null)
			{
				throw new ArgumentNullException("selectorExpression");
			}

			MemberExpression body = selectorExpression.Body as MemberExpression;
			if (body == null)
			{
				throw new ArgumentException("The body must be a member expression");
			}

			NotifyPropertyChanged (selectorExpression);
		}

		protected bool SetProperty<T>(ref T field, T value, Expression<Func<T>> selectorExpression)
        {
            if (EqualityComparer<T>.Default.Equals(field, value))
            {
                return false;
            }

            field = value;
			NotifyPropertyChanged (selectorExpression);
            
            return true;
        }
```
The property changed seems to work fine. I'm using the ChangeTrackingCollection<T> so that I am able to revert back to the collection state, removing newly added instances and restore deleted instances (if it's not added).

Problem is all newly added instances TrackingState is Unchanged and the EntityIdentifier is 00000000-0000-0000-0000-000000000000.

My portable class libraries target frameworks, .NET Framework 4.5, Windows Phone 8, .NET for Windows Store apps, Xamarin.Android, Xamarin.iOS, Xamarin.iOS (Classic).
I use the NuGet packages, TrackableEntities.Common and TrackableEntities.Client.

Any thoughts?

**Comment by xplatsolutions** [comment]
OK, I didn't notice the constructor passing a boolean if tracking should be enabled.

**Comment by tonysneed** [comment]
Ah yes, glad you figured it out. Thanks for your interest, and let me know if you have any other questions or ideas.
