### ISSUE TITLE
Client change tracking in Model?

### ISSUE THREAD

**Issue by xplatsolutions** [tonysneed/trackable-entities#79]
I think I miss something, I have my models deriving from EntityBase but it seems that when I create a new instance the TrackingState is Unchanged and as soon as I set a property to a new value it should mark the Model to Modified.

I see that in ChangeTrackingCollection you register in the PropertyChanged event and set the TrackingState, but I guess there is no similar functionality at the moment for models?

Shouldn't this be the case? I have a simple UnitTest like below but still doesn't work.

```
        [Test]
        public void ModelChangeTrackingToModified()
        {
            // Arrange
            Model model = new Model { TrackingState = TrackingState.UnChanged };
            
            // Act
            model.FirstName= "George";

            // Assert
            Assert.AreEqual(TrackingState.Modified, model.TrackingState); // It's always Unchanged
        }
```

Shouldn't the above be a valid scenario? For example I fetch a Model instance from my local database and when I take it back I should know if it is modified!

Thanks.

**Comment by tonysneed** [comment]
Hello @xplatsolutions,

My apologies -- I just realized this had gone unanswered. :innocent:  The way client-side change-tracking works is that a model needs to passed to a `ChangeTrackingCollection<T>`.  If it is already part of a collection, then all you need to do is set the `Tracking` property to `true` on the change tracker.  If it is a standalone model, as in your example, you will need to pass it to a change tracker, as shown below:

```csharp
[Fact]
public void Setting_Model_Property_Should_Mark_Model_As_Modified()
{
    // Arrange
    var model = new Person();
    var changeTracker = new ChangeTrackingCollection<Person>(model); // track changes

    // Act
    model.FirstName = "George";

    // Assert
    Assert.Equal(TrackingState.Modified, model.TrackingState);
}
```

However, this test will still fail if the model has not notified `changeTracker` that a change has taken place.  This is similar to how data binding works.  Property setters need to call a `NotifyPropertyChanged` method in the base class, which in turns fires a `PropertyChanged` event to which `changeTracker` is listening.

```csharp
public class Person : EntityBase
{
    private string _firstName;

    public string FirstName
    {
        get { return _firstName; }
        set
        {
            _firstName = value;
            NotifyPropertyChanged(); // Fire PropertyChanged event
        }
    }
}
```

The project templates which come with the VSIX installer for Trackable Entities includes T4 templates which generate models based on a database schema and call `NotifyPropertyChanged` in each setter.  As a result, trackable entities also support data binding out-of-the box.

I published a demo repo on GitHub which you can check out: https://github.com/tonysneed/Demo.ClientChangeTracking

Please let me know if this fully answers your question.

Cheers,
Tony

**Comment by xplatsolutions** [comment]
Hi @tonysneed,

I was hoping to avoid adding it to a collection, I checked the code and it seems it is possible to transfer some reflection code inside the EntityBase to support it; What do you think?

Other than that I guess maintaining a collection for a single entity needed to support tracking changes might not be a big deal.

Thanks,

**Comment by xplatsolutions** [comment]
Also, object graph change tracking is not supported right? E.g Order -> OrderDetails, when an OrderDetail instance is modified mark the Order parent instance as Modified as well.

**Comment by xplatsolutions** [comment]
Well scrap this, might not make sense it's something I need to support, kinda special.

**Comment by tonysneed** [comment]
Object graph change tracking is supported, by using `ChangeTrackingCollection<T>` for collection properties.  You'll see this demonstrated in the sample applications in the Trackable Entities repo.  Parent and children are tracked independently, so that the parent may remain unmodified while one or more children are modified.  You can call `GetChanges()` on the top-most change tracker to get a copy of the object graph with just the entities which have been added, modified or deleted.  There is a correlation mechanism which supports calling `MergeChanges` after persisting updates.

**Comment by xplatsolutions** [comment]
Actually I don't even use EF, I just use them client side with a SQLite local database.
I wanted the object graph parent modification for a specific scenario when a child is modified to get notified about it and save it. This would be accomplished via a chain of events I guess. Dirty job...
Thanks, I'll get it to work 

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 8:21 AM -0800, "Anthony Sneed" <notifications@github.com> wrote:












Object graph change tracking is supported, by using ChangeTrackingCollection<T> for collection properties.  You'll see this demonstrated in the sample applications in the Trackable Entities repo.  Parent and children are tracked independently, so that the parent may remain unmodified while one or more children are modified.  You can call GetChanges() on the top-most change tracker to get a copy of the object graph with just the entities which have been added, modified or deleted.  There is a correlation mechanism which supports calling MergeChanges after persisting updates.

**Comment by tonysneed** [comment]
The reflection code in `EntityBase` is an interesting idea.  The reason we went with the `INotifyPropertyChanged` interface is both for performance reasons and also for parity with data binding, which is usually a client-side concern.

If we want to incorporate change tracking into `EntityBase` then one way might be to add an implicit `ChangeTrackingCollection` to `EntityBase`.  Let me know if you're interested in that sort of thing.

**Comment by xplatsolutions** [comment]
Interesting thought! Set change tracking enabled in the model class and internally add it to a collection would do the job I guess. But this is an easy job for someone creating its own base class.
I think it's a nice workaround, and no need to move the reflection code in EntityBase.

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 8:27 AM -0800, "Anthony Sneed" <notifications@github.com> wrote:












The reflection code in EntityBase is an interesting idea.  The reason we went with the INotifyPropertyChanged interface is both for performance reasons and also for parity with data binding, which is usually a client-side concern.



If we want to incorporate change tracking into EntityBase then one way might be to add an implicit ChangeTrackingCollection to EntityBase.  Let me know if you're interested in that sort of thing.

**Comment by tonysneed** [comment]
To answer your last question, ChangeTrackingCollection does have an event which may help you: 

```csharp
[Fact]
public void Setting_Model_Property_Should_Mark_Fire_EntityChanged_Event()
{
    // Arrange
    var model = new Person();
    var changeTracker = new ChangeTrackingCollection<Person>(model);
    bool entityChanged = false;
    changeTracker.EntityChanged += (sender, args) => entityChanged = true;

    // Act
    model.FirstName = "George";

    // Assert
    Assert.True(entityChanged);
}
```

**Comment by tonysneed** [comment]
Yes, you can implement implicit change tracking in a class that inherits from `EntityBase`.  Then use the derived class as a base class for your entities.  That's a quick solution which should work.  I can update my demo repo with a sample if you wish.

**Comment by xplatsolutions** [comment]
Yes! I'll just have to chain the navigation properties to report to the parent and it will work.
I think it just needs little bit effort by the consumer developer, the project shouldn't changed since there are workarounds.

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 8:34 AM -0800, "Anthony Sneed" <notifications@github.com> wrote:












To answer your last question, ChangeTrackingCollection does have an event which may help you: 

[Fact]
public void Setting_Model_Property_Should_Mark_Fire_EntityChanged_Event()
{
    // Arrange
    var model = new Person();
    var changeTracker = new ChangeTrackingCollection<Person>(model);
    bool entityChanged = false;
    changeTracker.EntityChanged += (sender, args) => entityChanged = true;

    // Act
    model.FirstName = "George";

    // Assert
    Assert.True(entityChanged);
}

**Comment by xplatsolutions** [comment]
Of course, an example is always good!

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 8:36 AM -0800, "Anthony Sneed" <notifications@github.com> wrote:












Yes, you can implement implicit change tracking in a class that inherits from EntityBase.  Then use the derived class as a base class for your entities.  That's a quick solution which should work.  I can update my demo repo with a sample if you wish.

**Comment by tonysneed** [comment]
Alright, I pushed the sample to the [demo repo](https://github.com/tonysneed/Demo.ClientChangeTracking).  Here is the extended entity base class:

```csharp
public class ExtendedEntityBase<TEntity> : EntityBase where TEntity : class, ITrackable, INotifyPropertyChanged
{
    public ChangeTrackingCollection<TEntity> ChangeTracker { get; set; }

    protected void StartTracking(TEntity entity)
    {
        ChangeTracker = new ChangeTrackingCollection<TEntity>(entity);
    }
}
```

Here is the refactored Person class:

```csharp
public class Person : ExtendedEntityBase<Person>
{
    public Person()
    {
        StartTracking(this);
    }

    private string _firstName;

    public string FirstName
    {
        get { return _firstName; }
        set
        {
            _firstName = value;
            NotifyPropertyChanged();
        }
    }
}
```

**Comment by tonysneed** [comment]
If you make the navigation properties of type ChangeTrackingCollection, then you can set a Parent property on it, so that graph traversal will take place. Happy to update the demo repo with that code too. :)

**Comment by xplatsolutions** [comment]
Alright! Looks good!
Thanks for the support and the discussion.

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 9:13 AM -0800, "Anthony Sneed" <notifications@github.com> wrote:










If you make the navigation properties of type ChangeTrackingCollection, then you can set a Parent property on it, so that graph traversal will take place. Happy to update the demo repo with that code too. :)

**Comment by tonysneed** [comment]
I updated the demo repo to include a sample of change tracking with both reference and child properties: tonysneed/Demo.ClientChangeTracking@2e73f00247a06bec7761f60486b9c04a4f73f05f.  Enjoy. :smile:

**Comment by xplatsolutions** [comment]
Amazing! Looks good, will try later tonight.
Will you update the Nuget repo?

--
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405




On Wed, Dec 9, 2015 at 1:00 PM -0800, "Anthony Sneed" <notifications@github.com> wrote:












I updated the demo repo to include a sample of change tracking with both reference and child properties: tonysneed/Demo.ClientChangeTracking@2e73f00.  Enjoy.

**Comment by tonysneed** [comment]
You mean the NuGet package? Don't see a need to update that at this point, as you can add the extended base class yourself from the code in the demo repo.

**Comment by xplatsolutions** [comment]
I checked the code, the ExtendedEntityBase is a helpful example and I can solve the first problem with adding a ChangeTracker for each entity or derive all from ExtendedEntityBase.

I didn't get how I can solve the children -> update parent relationship, is it possible?

Example.

```
       [Fact]
        public void Setting_Reference_Property_Should_Mark_Parent_As_Modified()
        {
            // Arrange
            var model = new Person();
            model.Location = new Location {City = "London"};
            model.StartTracking();

            // Act
            model.Location.City = "Rome";

            // Assert
            Assert.Equal(TrackingState.Modified, model.Location.TrackingState);
            Assert.Equal(TrackingState.Modified, model.TrackingState);
        }
```

**Comment by tonysneed** [comment]
I updated the demo repo to support updating a parent entity when there are changes in the object graph. tonysneed/Demo.ClientChangeTracking@390fc53eef47c0a7c5dc160dd9f2b6f9e9abb1e5.

I added tests for both reference and child properties.  Hope you like.

**Comment by tonysneed** [comment]
Made couple of other small changes. This is the latest commit:
tonysneed/Demo.ClientChangeTracking@a484fdd8659aa82b881c80fa3461390394e07310

**Comment by xplatsolutions** [comment]
Works great!

Thanks for the update.

—
George Taskos
Xplat Software Architect
m: +1 (415) 900-7405

**Comment by tonysneed** [comment]
Closing this issue, as it seems we've answered the questions. Glad to be of help!

**Comment by xplatsolutions** [comment]
Thanks for the help, I appreciate it.
