### ISSUE TITLE
Support for multiple primary keys for reference types

### ISSUE THREAD

**Issue by Kanogi** [tonysneed/trackable-entities#83]
Is there any plans to implement this in the near future?

We have a project that has hundreds of tables containing multiple primary keys.
Is there any solution for this?

**Comment by tonysneed** [comment]
I don't see why composite primary keys would not be allowed.  Entity Framework supports that scenario.  @Kanogi, can you please provide an example of what you are tying to do and the error you're receiving?

**Comment by HDB2000** [comment]
Tony,

I ran across an issue with this when I first started working with Trackable Entities.  The composite key had been added to my table just to accomplish something with an earlier version of EF, so I just removed it and moved on.  Thanks for a great tool!

Anyway, I think the issue was here in DbContextExtensions, where the count of members in the primary key has to be 1.

    private static string GetPrimaryKeyName(this DbContext dbContext, System.Type entityType)
    {
      EntityType edmSpaceType = DbContextExtensions.GetEdmSpaceType(dbContext, entityType);
      if (edmSpaceType == null)
        return (string) null;
      if (((ReadOnlyCollection<EdmMember>) ((EntityTypeBase) edmSpaceType).get_KeyMembers()).Count > 1)
        return (string) null;
      return Enumerable.FirstOrDefault<string>(Enumerable.Select<EdmMember, string>((IEnumerable<EdmMember>) ((EntityTypeBase) edmSpaceType).get_KeyMembers(), (Func<EdmMember, string>) (k => k.get_Name())));
    }

**Comment by tonysneed** [comment]
@azabluda, Would you happen to have any time to look at this? Thanks!

**Comment by azabluda** [comment]
@tonysneed Being on a business trip until the end on the next week, I could only have a very brief look at the `GetPrimaryKeyName` function. If I'm not mistaken it is only used by `LoadRelatedEntities` extension method, which always looked to me a bit alien to TE and limited in many ways. I would rather opt for excluding it from the standard distribution.

If `LoadRelatedEntities` is the only method which requires single PKs, then my advice to @HDB2000 would be to just try go without it.

Apart from that I join Tony's [comment](https://github.com/tonysneed/trackable-entities/issues/83#issuecomment-161214534) and would appreciate an example (ideally a failing unit test) to speed up the development of the missing feature.
