### ISSUE TITLE
WCF service and DataContract/DataMember in client entities

### ISSUE THREAD

**Issue by linqueue** [tonysneed/trackable-entities#84]
Hi Toni,
first, thanks for a very useful extension!
I'm observing a strange behavior during probing the WCF scenario with different service/client entities.
My problem is that the receiving site do not see the data (IEnumerable<Job> jobs = queueService.GetJobs().Result) until I add DataContract and /DataMember attributes to the Job entity.
If I've understood correctly the attributes are not needed anymore since ModelBase<TModel> is replaced by the EntityBase.
The namespaces on the client and service site are the same.

Thanks in advance,
Andrej

**Comment by tonysneed** [comment]
Hello @linqueue,

Glad you like the extension!  The DataContractSerializer is able to handle entities without `[DataContract]` and `[DataMember]` if your classes are public and your properties are read-write and public.  However, that won't work if your entities have **cyclical references** (for example, Product has Category and Category has Products).  In that case, you'll want to use a helper package I built, which configures the DCS to handle cycles without requiring the `[DataContract]` and `[DataMember]` attributes.

The NuGet package is called **WcfSerializationHelper**, and you add it to the project containing your ServiceContract.  Then place the following attribute on your service contracts: `[DataContractSerializerPreserveReferences]`.  You only have to do this on the service-side.

For an example, see the WCF sample for VS 2013: https://github.com/tonysneed/trackable-entities/tree/develop/Samples/VS2013/WcfSample/WcfSample.Service.Core.

Cheers!
Tony

**Comment by linqueue** [comment]
Hi @tonysneed,

thanks - this didn't help directly but gave me a hint: I've created my solution by VS2015. Repeating the steps under VS2013 gave me a working solution. I guess the VS2015 extension is too old (v2.2.0). Copying few fragments from VS2013 solution into my VS2015 solution (containing several other projects) fixed the issue. There are plans to refresh the VS2015 VSIX?

Regards,
Andrej

**Comment by tonysneed** [comment]
@linqueue: Yes, in fact I am planning to get the VS2015 extension out this month.  There's been a delay because I needed to change the way in which NuGet packages are included in the VSIX: https://github.com/NuGet/Home/issues/598.  So keep an eye out this month for the VS2015 release of the extension for Trackable Entities.
